// FADU Bubble Wheel — FADU 전용 구슬 레이스 맵 (기본 첫 번째 맵).
// 초반 BubblePop식 구간(출발 bubble, spin gate, FADU 글자 peg, 갈림길 레인, windmill, bubble wall) → 막판 Wheel of fortune식 회전 막대 피날레.
// 지형 아이디어·일부 좌표는 lazygyu/roulette의 'Wheel of fortune' / 'BubblePop' 맵을 참고해 변형함 (MIT, lib/marble/LICENSE).
export const fadu = {
  title: 'FADU Bubble Wheel',
  goalY: 91.5,
  zoomY: 88,
  entities: [
    // 바깥 벽 (왼쪽 / 오른쪽). 시작 chute x 9.25~16.5는 원본과 같음
    { type: 'static', position: { x: 0, y: 0 }, props: { density: 1, angularVelocity: 0, restitution: 0 }, shape: { type: 'polyline', rotation: 0, points: [[9.25, -300], [9.25, 16], [5.5, 19.5], [5.5, 29], [7.5, 32], [7.5, 45], [6.5, 47], [6.5, 54.5], [9.25, 58], [9.25, 74], [5.5, 77], [5.5, 79], [12.4, 88], [12.4, 93]] } },
    { type: 'static', position: { x: 0, y: 0 }, props: { density: 1, angularVelocity: 0, restitution: 0 }, shape: { type: 'polyline', rotation: 0, points: [[16.5, -300], [16.5, 16], [20, 19.5], [20, 29], [18, 32], [18, 45], [19, 47], [19, 54.5], [16.5, 58], [16.5, 74], [20, 77], [20, 79], [13.45, 88], [13.45, 93]] } },
    // y 5.5 · 출발 bubble 4개 (닿으면 터짐): 소수 인원 경기에서 출발 칸에 따른 유불리를 줄임
    { type: 'static', position: { x: 11.15, y: 5.5 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.45 } },
    { type: 'static', position: { x: 12.95, y: 5.5 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.45 } },
    { type: 'static', position: { x: 14.75, y: 5.5 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.45 } },
    { type: 'static', position: { x: 16, y: 5.5 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.45 } },
    // y 10~14 · Spin gate (BubblePop): 빠른 mini spinner 3개 + 서로 반대로 도는 긴 bar 2개
    { type: 'kinematic', position: { x: 10.7, y: 10 }, props: { density: 1, angularVelocity: 10, restitution: 0 }, shape: { type: 'box', width: 0.5, height: 0.1, rotation: 0 } },
    { type: 'kinematic', position: { x: 12.7, y: 10 }, props: { density: 1, angularVelocity: 10, restitution: 0 }, shape: { type: 'box', width: 0.5, height: 0.1, rotation: 0 } },
    { type: 'kinematic', position: { x: 14.7, y: 10 }, props: { density: 1, angularVelocity: -10, restitution: 0 }, shape: { type: 'box', width: 0.5, height: 0.1, rotation: 0 } },
    { type: 'kinematic', position: { x: 10.7, y: 14 }, props: { density: 1, angularVelocity: -3, restitution: 0 }, shape: { type: 'box', width: 2, height: 0.1, rotation: 0 } },
    { type: 'kinematic', position: { x: 14.7, y: 14 }, props: { density: 1, angularVelocity: 3, restitution: 0 }, shape: { type: 'box', width: 2, height: 0.1, rotation: 0 } },
    // y 21.5~25.5 · FADU dot-matrix 글자 (3x5, 간격 1.0 → 틈 0.66 > 구슬 지름) = Galton board + 양옆 peg
    { type: 'static', position: { x: 6.65, y: 21.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 7.65, y: 21.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 8.65, y: 21.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 6.65, y: 22.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 6.65, y: 23.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 7.65, y: 23.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 6.65, y: 24.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 6.65, y: 25.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 11.05, y: 21.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 10.05, y: 22.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 12.05, y: 22.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 10.05, y: 23.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 11.05, y: 23.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 12.05, y: 23.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 10.05, y: 24.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 12.05, y: 24.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 10.05, y: 25.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 12.05, y: 25.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 13.45, y: 21.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 14.45, y: 21.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 13.45, y: 22.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 15.45, y: 22.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 13.45, y: 23.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 15.45, y: 23.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 13.45, y: 24.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 15.45, y: 24.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 13.45, y: 25.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 14.45, y: 25.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 16.85, y: 21.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 18.85, y: 21.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 16.85, y: 22.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 18.85, y: 22.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 16.85, y: 23.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 18.85, y: 23.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 16.85, y: 24.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 18.85, y: 24.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 16.85, y: 25.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 17.85, y: 25.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 18.85, y: 25.5 }, props: { density: 1, angularVelocity: 0, restitution: 0.3 }, shape: { type: 'circle', radius: 0.17, color: '#ff3b5c' } },
    { type: 'static', position: { x: 7, y: 20.1 }, props: { density: 1, angularVelocity: 0, restitution: 0 }, shape: { type: 'box', width: 0.2, height: 0.2, rotation: 0.785 } },
    { type: 'static', position: { x: 18.5, y: 20.1 }, props: { density: 1, angularVelocity: 0, restitution: 0 }, shape: { type: 'box', width: 0.2, height: 0.2, rotation: 0.785 } },
    // y 33~46 · diamond splitter (닫힌 polyline) → 레인 2개
    { type: 'static', position: { x: 0, y: 0 }, props: { density: 1, angularVelocity: 0, restitution: 0 }, shape: { type: 'polyline', rotation: 0, points: [[12.75, 33], [11.25, 34.5], [11.25, 44], [12.75, 46], [14.25, 44], [14.25, 34.5], [12.75, 33]] } },
    // 왼쪽 레인: 지그재그 선반 3개
    { type: 'static', position: { x: 0, y: 0 }, props: { density: 1, angularVelocity: 0, restitution: 0 }, shape: { type: 'polyline', rotation: 0, points: [[7.5, 34.8], [10, 37.2]] } },
    { type: 'static', position: { x: 0, y: 0 }, props: { density: 1, angularVelocity: 0, restitution: 0 }, shape: { type: 'polyline', rotation: 0, points: [[11.25, 37.8], [8.75, 40.2]] } },
    { type: 'static', position: { x: 0, y: 0 }, props: { density: 1, angularVelocity: 0, restitution: 0 }, shape: { type: 'polyline', rotation: 0, points: [[7.5, 40.8], [10, 43.2]] } },
    // 오른쪽 레인: spinner + pop bubble 3개 + peg 2개
    { type: 'kinematic', position: { x: 16.125, y: 36.2 }, props: { density: 1, angularVelocity: 6, restitution: 0 }, shape: { type: 'box', width: 0.9, height: 0.1, rotation: 0 } },
    { type: 'static', position: { x: 15.2, y: 39.6 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.45 } },
    { type: 'static', position: { x: 17.05, y: 39.6 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.45 } },
    { type: 'static', position: { x: 16.125, y: 41.6 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.5 } },
    { type: 'static', position: { x: 15, y: 43.4 }, props: { density: 1, angularVelocity: 0, restitution: 0 }, shape: { type: 'box', width: 0.15, height: 0.15, rotation: 0.785 } },
    { type: 'static', position: { x: 17.25, y: 43.4 }, props: { density: 1, angularVelocity: 0, restitution: 0 }, shape: { type: 'box', width: 0.15, height: 0.15, rotation: 0.785 } },
    // y 51.5 · 주황 windmill (십자, 벽과 3.6 이상 떨어짐)
    { type: 'kinematic', position: { x: 12.75, y: 51.5 }, props: { density: 1, angularVelocity: -1.3, restitution: 0 }, shape: { type: 'box', width: 2.4, height: 0.1, rotation: 0, color: '#ffb000' } },
    { type: 'kinematic', position: { x: 12.75, y: 51.5 }, props: { density: 1, angularVelocity: -1.3, restitution: 0 }, shape: { type: 'box', width: 2.4, height: 0.1, rotation: 1.571, color: '#ffb000' } },
    // y 60~67 · Bubble wall (BubblePop): 닿으면 터지는 bubble 10개, 선두를 튕겨 무리와 간격을 좁힘
    { type: 'static', position: { x: 10.6, y: 60.5 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.5 } },
    { type: 'static', position: { x: 12.875, y: 60.5 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.5 } },
    { type: 'static', position: { x: 15.15, y: 60.5 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.5 } },
    { type: 'static', position: { x: 11.74, y: 62.5 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.5 } },
    { type: 'static', position: { x: 14.01, y: 62.5 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.5 } },
    { type: 'static', position: { x: 12.875, y: 64.7 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.7 } },
    { type: 'static', position: { x: 10.4, y: 65.7 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.5 } },
    { type: 'static', position: { x: 15.35, y: 65.7 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.5 } },
    { type: 'static', position: { x: 11.6, y: 67.7 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.5 } },
    { type: 'static', position: { x: 14.15, y: 67.7 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.5 } },
    // y 71 · Wheel of fortune식 회전 bar 한 줄
    { type: 'kinematic', position: { x: 10.05, y: 71 }, props: { density: 1, angularVelocity: 3.5, restitution: 0 }, shape: { type: 'box', width: 1.35, height: 0.1, rotation: 0 } },
    { type: 'kinematic', position: { x: 12.875, y: 71 }, props: { density: 1, angularVelocity: -3.5, restitution: 0 }, shape: { type: 'box', width: 1.35, height: 0.1, rotation: 0 } },
    { type: 'kinematic', position: { x: 15.7, y: 71 }, props: { density: 1, angularVelocity: 3.5, restitution: 0 }, shape: { type: 'box', width: 1.35, height: 0.1, rotation: 0 } },
    // y 88 = zoomY · 피날레 sweeping bar (pivot은 왼쪽 경사 벽 뒤, 끝이 출구 입구를 쓸고 지나감)
    { type: 'kinematic', position: { x: 11.45, y: 88 }, props: { density: 1, angularVelocity: -1.1, restitution: 0 }, shape: { type: 'box', width: 2, height: 0.1, rotation: 0, color: '#ff4d6d' } },
    // 오른쪽 경사 pusher bar: 경사에 머문 구슬을 출구 쪽으로 퍼 나름
    { type: 'kinematic', position: { x: 16.398, y: 83.95 }, props: { density: 1, angularVelocity: -1.6, restitution: 0 }, shape: { type: 'box', width: 1.8, height: 0.1, rotation: 0, color: '#ff4d6d' } },
    // y 80~86 · 최종 bowl bubble 5개
    { type: 'static', position: { x: 15.05, y: 85.6 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.45 } },
    { type: 'static', position: { x: 10.6, y: 84.8 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.45 } },
    { type: 'static', position: { x: 9.3, y: 80.5 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.45 } },
    { type: 'static', position: { x: 16.4, y: 80.5 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.45 } },
    { type: 'static', position: { x: 12.85, y: 82.6 }, props: { density: 1, angularVelocity: 0, restitution: 1.5, life: 1 }, shape: { type: 'circle', radius: 0.45 } },
  ],
};
